version: '3.8'

services:
  absence-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: absence-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
    volumes:
      # Persistance de la base de données SQLite
      - absence_data:/app/data
      # Montage des logs (optionnel)
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); http.get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1));"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - absence_network

  # Service optionnel pour la surveillance (décommentez si nécessaire)
  # adminer:
  #   image: adminer:latest
  #   container_name: absence-adminer
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - ADMINER_DEFAULT_SERVER=absence-api
  #   depends_on:
  #     - absence-api
  #   networks:
  #     - absence_network

volumes:
  absence_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  absence_network:
    driver: bridge