name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run quick tests
      run: |
        echo "🧪 Running quick validation for Dependabot PR"
        # Run basic validation
        npm run lint --if-present || echo "No lint script found"
        npm test --if-present || echo "No test script found"
        
    - name: Auto-approve Dependabot PRs
      if: success()
      run: |
        echo "✅ Auto-approving Dependabot PR"
        # This would typically use GitHub CLI or API
        # gh pr review --approve "$PR_URL"
        
    - name: Enable auto-merge for Dependabot PRs
      if: success()
      run: |
        echo "🤖 Enabling auto-merge for Dependabot PR"
        # This would typically use GitHub CLI or API
        # gh pr merge --auto --merge "$PR_URL"